hash -d b=~/bin
hash -d c=~/Cours
hash -d calgo=~/Cours/Algorithmique
hash -d cdroit=~/Cours/Droit
hash -d call=~/Cours/Allemand
hash -d cen=~/Cours/Anglais
hash -d ccom=~/Cours/Communication
hash -d cemn=~/Cours/"Ecriture Medias"
hash -d chda=~/Cours/"Histoire Art"
hash -d cin=~/Cours/"Images Numeriques"
hash -d cinfo=~/Cours/Infographie
hash -d ciw=~/Cours/"Integration Web"
hash -d cpav=~/Cours/"Prod Audiovisuelle"
hash -d crsx=~/Cours/Reseaux
hash -d cmaths=~/Cours/Maths
hash -d cburo=~/Cours/Bureautique
hash -d cmerca=~/Cours/Mercatique
hash -d cdg=~/Cours/"Design Graphique"
hash -d d=~/Documents
hash -d git=~/Documents/Git
hash -d i=~/Images
hash -d iw=~/Images/wallpapers
hash -d is=~/Images/Screenshots
hash -d l=~/Livres
hash -d lc=~/Livres/Comics
hash -d lp=~/Livres/Programmation
hash -d lr=~/Livres/Romans
hash -d m=~/Musique
hash -d ml=~/Musique/.lyrics
hash -d dl=~/Téléchargements
hash -d dlt=~/Téléchargements/Torrents
hash -d v=~/Vidéos
hash -d tmp=~/tmp
hash -d conf=~/.config
hash -d data=~/.local/share
hash -d zsh=~/.config/zsh
hash -d xmo=~/.xmonad
hash -d rto=~/.rTorrent

hash -d prb=~/Documents/Programmation/Ruby
hash -d phs=~/Documents/Programmation/Haskell
