imap á &aacute;
imap é &eacute;
imap í &iacute;
imap ó &oacute;
imap ú &uacute;
imap ü &uuml;
imap ñ &ntilde;
imap Á &Aacute;
imap É &Eacute;
imap Í &Iacute;
imap Ó &Oacute;
imap Ú &Uacute;
imap Ü &Uuml;
imap Ñ &Ntilde;
imap ¡ &iexcl;
imap ¿ &iquest;
imap è &egrave;
imap à &agrave;
imap @c &copy
imap @tm &reg
imap à &agrave
imap â &circ
imap ä &auml
imap ç &ccedil
imap è &egrave
imap ê &ecirc
imap ë &euml
imap ù &ugrave
imap û &ucirc
imap ü &uuml
